site_name: Triad Tutors
site_url: https://triadtutors.github.io/triadtutors/

plugins:
  - glightbox

theme:
  name: material
  icon:
    admonition:
      info: material/hand-pointing-up

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences